# Generated by Django 4.2.3 on 2023-07-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendsprofile',
            old_name='user',
            new_name='name',
        ),
    ]
